import { getT } from "@/i18n/server";
import type { IncidentDetail } from "@/lib/incidents";
import { toggleTask } from "./actions";
import { draftPostMortemAction, setPostMortemStatus } from "./ai-actions";
import { SectionEditor } from "./section-editor";
import { exportPostMortemAction } from "./docs-actions";

/**
 * IN-04 — the post-incident flow: the two phases as checklists on the left
 * (documenting, then reviewing), the debrief card, and the post-mortem on the
 * right with its sections — edited in place, drafted or regenerated by the
 * assistant when the workspace allows, always labelled as a draft.
 */
export async function PostIncident({
  inc,
  number,
  canAct,
  postMortemTerm = null,
  aiAllowed = false,
  docs = [],
  exportError = null,
}: {
  inc: IncidentDetail;
  number: number;
  canAct: boolean;
  /** The workspace's own word for its post-mortem; the product's when unset. */
  postMortemTerm?: string | null;
  /** Whether the assistant may draft the post-mortem for this workspace. */
  aiAllowed?: boolean;
  /** Documentation tools connected to the workspace — where the post-mortem can be exported. */
  docs?: Array<{ kind: "confluence" | "notion"; label: string }>;
  exportError?: string | null;
}) {
  const t = await getT();
  const phases = ["documenting", "reviewing"] as const;
  const draftBtn: React.CSSProperties = {
    height: 32,
    padding: "0 13px",
    border: "1px solid var(--viol)",
    borderRadius: 8,
    background: "var(--panel)",
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--viol)",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  };
  const pmNext: Record<string, "in_review" | "completed" | null> = {
    in_progress: "in_review",
    in_review: "completed",
    completed: null,
  };

  if (inc.tasks.length === 0 && !inc.postMortem) {
    return (
      <div
        className="oi-rise"
        style={{
          maxWidth: 760,
          padding: 28,
          border: "1.5px dashed var(--line)",
          borderRadius: 14,
          textAlign: "center",
          color: "var(--ink-3)",
          fontSize: 13.5,
          background: "var(--panel)",
        }}
      >
        {inc.row.phase === "closed" || inc.row.phase === "post_incident"
          ? t("postIncident.noneYet")
          : t("postIncident.notStarted")}
        {canAct &&
          aiAllowed &&
          (inc.row.phase === "closed" || inc.row.phase === "post_incident") && (
            <form action={draftPostMortemAction} style={{ marginTop: 14 }}>
              <input type="hidden" name="number" value={number} />
              <button type="submit" data-testid="pm-draft" style={draftBtn}>
                ✦ {t("postMortem.draftWithAi")}
              </button>
            </form>
          )}
      </div>
    );
  }

  return (
    <div
      className="oi-rise"
      style={{
        display: "grid",
        gridTemplateColumns: "320px minmax(0, 1fr)",
        gap: 16,
        alignItems: "start",
      }}
    >
      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
        {phases.map((phase) => {
          const tasks = inc.tasks.filter((x) => x.phase === phase);
          if (tasks.length === 0) return null;
          const done = tasks.filter((x) => x.completedAt || x.skippedAt).length;
          const complete = done === tasks.length;
          return (
            <div
              key={phase}
              className="oi-panel"
              style={{ padding: "14px 16px", display: "flex", flexDirection: "column", gap: 9 }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                {complete ? (
                  <span
                    style={{
                      width: 18,
                      height: 18,
                      borderRadius: "50%",
                      background: "var(--ok)",
                      color: "#fff",
                      display: "grid",
                      placeItems: "center",
                      fontSize: 10,
                      fontWeight: 700,
                    }}
                  >
                    ✓
                  </span>
                ) : (
                  <span
                    style={{
                      width: 18,
                      height: 18,
                      borderRadius: "50%",
                      border: "2px solid var(--brand)",
                      display: "inline-block",
                    }}
                  />
                )}
                <span style={{ fontSize: 13.5, fontWeight: 600 }}>
                  {t(`postIncident.phase.${phase}`)}
                </span>
                <span style={{ flex: 1 }} />
                <span
                  style={{
                    fontSize: 12,
                    fontWeight: 600,
                    color: complete ? "var(--ok)" : "var(--ink-2)",
                  }}
                >
                  {done}/{tasks.length}
                </span>
              </div>
              {tasks.map((task) => {
                const isDone = Boolean(task.completedAt || task.skippedAt);
                const meta = [
                  task.assigneeName,
                  task.skippedAt
                    ? t("postIncident.skipped", { reason: task.skipReason ?? "" })
                    : task.completedAt
                      ? t("postIncident.doneOn", { date: t.fmt.dateShort(task.completedAt) })
                      : task.dueAt
                        ? t("postIncident.dueOn", { date: t.fmt.dateShort(task.dueAt) })
                        : null,
                ]
                  .filter(Boolean)
                  .join(" · ");
                return (
                  <div
                    key={task.id}
                    style={{ display: "flex", alignItems: "flex-start", gap: 9, fontSize: 13 }}
                  >
                    <form action={toggleTask} style={{ display: "contents" }}>
                      <input type="hidden" name="id" value={task.id} />
                      <input type="hidden" name="number" value={number} />
                      <button
                        type="submit"
                        disabled={!canAct}
                        aria-pressed={isDone}
                        aria-label={task.title}
                        style={{
                          width: 16,
                          height: 16,
                          flex: "none",
                          marginTop: 2,
                          borderRadius: 5,
                          border: `1.5px solid ${isDone ? "var(--ok)" : "var(--line)"}`,
                          background: isDone ? "var(--ok)" : "var(--panel)",
                          display: "grid",
                          placeItems: "center",
                          color: "#fff",
                          fontSize: 9,
                          fontWeight: 700,
                          cursor: canAct ? "pointer" : "default",
                          padding: 0,
                        }}
                      >
                        {isDone ? "✓" : ""}
                      </button>
                    </form>
                    <span style={{ flex: 1, minWidth: 0 }}>
                      <span
                        style={{
                          display: "block",
                          fontWeight: 500,
                          textDecoration: isDone ? "line-through" : "none",
                          color: isDone ? "var(--ink-3)" : "var(--ink)",
                        }}
                      >
                        {task.title}
                      </span>
                      {meta && (
                        <span
                          style={{
                            display: "block",
                            fontSize: 11.5,
                            color: "var(--ink-3)",
                            marginTop: 1,
                          }}
                        >
                          {meta}
                        </span>
                      )}
                    </span>
                  </div>
                );
              })}
              {phase === "reviewing" && (
                <div
                  style={{
                    fontSize: 12,
                    color: "var(--ink-3)",
                    borderTop: "1px solid var(--line-2)",
                    paddingTop: 8,
                  }}
                >
                  {t("postIncident.skipNote")}
                </div>
              )}
            </div>
          );
        })}
        {inc.debrief && (
          <div
            style={{
              background: "var(--sunk)",
              borderRadius: 14,
              padding: "12px 14px",
              display: "flex",
              flexDirection: "column",
              gap: 4,
            }}
          >
            <div style={{ fontSize: 13, fontWeight: 600 }}>
              {t("postIncident.debrief", {
                date: t.fmt.dateShort(inc.debrief.scheduledAt),
                from: t.fmt.time(inc.debrief.scheduledAt, t.timeZone),
                to: t.fmt.time(
                  new Date(
                    inc.debrief.scheduledAt.getTime() + inc.debrief.durationMinutes * 60_000,
                  ),
                  t.timeZone,
                ),
              })}
            </div>
            <div style={{ fontSize: 12.5, color: "var(--ink-3)" }}>
              {t("postIncident.debriefGuests", { count: inc.debrief.attendees.length })}
              {inc.debrief.invitationSentAt ? ` ${t("postIncident.invitationSent")}` : ""}
            </div>
          </div>
        )}
      </div>

      {inc.postMortem && (
        <div className="oi-panel" style={{ overflow: "hidden" }}>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 10,
              padding: "13px 20px",
              borderBottom: "1px solid var(--line)",
            }}
          >
            <span style={{ fontFamily: "var(--font-title)", fontSize: 15, fontWeight: 600 }}>
              {postMortemTerm ?? t("postMortem.title")}
            </span>
            <span
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 6,
                padding: "3px 10px 3px 8px",
                borderRadius: 999,
                background: inc.postMortem.status === "completed" ? "var(--ok-t)" : "var(--open-t)",
                color: inc.postMortem.status === "completed" ? "var(--ok)" : "var(--open)",
                fontSize: 11.5,
                fontWeight: 600,
              }}
            >
              <span
                style={{ width: 5, height: 5, borderRadius: "50%", background: "currentColor" }}
              />
              {t(`postMortem.status.${inc.postMortem.status}`)}
            </span>
            <span style={{ flex: 1 }} />
            {canAct &&
              aiAllowed &&
              inc.postMortem.sections.every((sec) => sec.body.trim() === "") && (
                <form action={draftPostMortemAction} style={{ display: "contents" }}>
                  <input type="hidden" name="number" value={number} />
                  <button type="submit" data-testid="pm-draft" style={draftBtn}>
                    ✦ {t("postMortem.draftWithAi")}
                  </button>
                </form>
              )}
            {inc.postMortem.externalUrl && (
              <a
                href={inc.postMortem.externalUrl}
                target="_blank"
                rel="noreferrer"
                className="oi-link"
                data-testid="pm-external-link"
                style={{ fontSize: 12.5, fontWeight: 600 }}
              >
                {t("postMortem.exported")} ↗
              </a>
            )}
            {canAct &&
              docs.length > 0 &&
              inc.postMortem.sections.some((sec) => sec.body.trim() !== "") &&
              docs.map((d) => (
                <form key={d.kind} action={exportPostMortemAction} style={{ display: "contents" }}>
                  <input type="hidden" name="number" value={number} />
                  <input type="hidden" name="kind" value={d.kind} />
                  <button
                    type="submit"
                    data-testid={`pm-export-${d.kind}`}
                    className="oi-hover"
                    style={{
                      height: 32,
                      padding: "0 12px",
                      border: "1px solid var(--line)",
                      borderRadius: 8,
                      background: "var(--panel)",
                      fontSize: 12.5,
                      fontWeight: 500,
                      cursor: "pointer",
                    }}
                  >
                    {t("postMortem.exportTo", { tool: d.label })}
                  </button>
                </form>
              ))}
            {canAct && pmNext[inc.postMortem.status] && (
              <form action={setPostMortemStatus} style={{ display: "contents" }}>
                <input type="hidden" name="number" value={number} />
                <input type="hidden" name="status" value={pmNext[inc.postMortem.status]!} />
                <button
                  type="submit"
                  style={{
                    height: 32,
                    padding: "0 13px",
                    borderRadius: 8,
                    background: "var(--brand)",
                    color: "#fff",
                    border: 0,
                    fontSize: 12.5,
                    fontWeight: 600,
                    cursor: "pointer",
                  }}
                >
                  {inc.postMortem.status === "in_progress"
                    ? t("postMortem.sendToReview")
                    : t("postMortem.markCompleted")}
                </button>
              </form>
            )}
          </div>
          {exportError && (
            <div
              role="alert"
              style={{
                padding: "8px 20px",
                fontSize: 12.5,
                color: "var(--dang)",
                borderBottom: "1px solid var(--line)",
              }}
            >
              {exportError}
            </div>
          )}
          {inc.postMortem.aiDrafted && (
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 9,
                background: "var(--viol-t)",
                padding: "9px 20px",
                borderBottom: "1px solid var(--line)",
                fontSize: 12.5,
                color: "var(--viol)",
              }}
            >
              <span
                style={{
                  fontWeight: 700,
                  fontSize: 10.5,
                  letterSpacing: ".08em",
                  background: "var(--panel)",
                  borderRadius: 6,
                  padding: "2px 7px",
                }}
              >
                {t("postMortem.aiDraftTag")}
              </span>
              {t("postMortem.aiDraftNote")}
            </div>
          )}
          <div style={{ padding: "22px 26px", maxWidth: 700 }}>
            <div
              style={{
                fontFamily: "var(--font-title)",
                fontSize: 19,
                fontWeight: 600,
                letterSpacing: "-.015em",
              }}
            >
              INC-{number} — {inc.row.name}
            </div>
            <div style={{ fontSize: 12.5, color: "var(--ink-3)", margin: "6px 0 18px" }}>
              {[
                inc.row.severityName,
                t.fmt.dateShort(inc.row.declaredAt),
                inc.row.resolvedAt
                  ? t("postMortem.detectionToResolution", {
                      duration: t.fmt.duration(
                        (inc.row.resolvedAt.getTime() - inc.row.declaredAt.getTime()) / 60_000,
                      ),
                    })
                  : null,
                inc.postMortem.ownerName
                  ? t("postMortem.ownedBy", { name: inc.postMortem.ownerName })
                  : null,
              ]
                .filter(Boolean)
                .join(" · ")}
            </div>
            {inc.postMortem.sections.map((sec) => (
              <SectionEditor
                key={sec.key}
                number={number}
                section={sec}
                canAct={canAct}
                aiAllowed={aiAllowed}
              />
            ))}
            {inc.followUps.length > 0 && (
              <>
                <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 5 }}>
                  {t("incident.tab.followUps")}
                </div>
                <ul
                  style={{
                    margin: 0,
                    paddingLeft: 20,
                    fontSize: 13.5,
                    color: "var(--ink-2)",
                    lineHeight: 1.65,
                  }}
                >
                  {inc.followUps.map((f) => (
                    <li key={f.id}>
                      {f.title} — <strong>{f.priorityName}</strong>,{" "}
                      {f.status === "done"
                        ? t("followUp.status.done").toLowerCase()
                        : t("followUp.status.open").toLowerCase()}
                      {f.externalRef ? ` (${f.externalRef.key})` : ""}
                    </li>
                  ))}
                </ul>
              </>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
