"use client";

import { useState } from "react";
import { useT } from "@/i18n/client";
import { draftPostMortemAction, savePostMortemSection } from "./ai-actions";

/**
 * One post-mortem section: read as prose or bullets, edited in place as text,
 * regenerated by the assistant when allowed. The person's edit always wins.
 */
export function SectionEditor({
  number,
  section,
  canAct,
  aiAllowed,
}: {
  number: number;
  section: { key: string; title: string; body: string };
  canAct: boolean;
  aiAllowed: boolean;
}) {
  const t = useT();
  const [editing, setEditing] = useState(false);
  const small: React.CSSProperties = {
    background: "none",
    border: 0,
    padding: 0,
    fontSize: 11.5,
    fontWeight: 600,
    cursor: "pointer",
    color: "var(--brand)",
  };
  return (
    <div data-testid={`pm-section-${section.key}`} style={{ marginBottom: 16 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 5 }}>
        <span style={{ fontSize: 14, fontWeight: 600 }}>{section.title}</span>
        <span style={{ flex: 1 }} />
        {canAct && !editing && (
          <>
            <button type="button" onClick={() => setEditing(true)} style={small}>
              {t("common.edit")}
            </button>
            {aiAllowed && (
              <form action={draftPostMortemAction} style={{ display: "contents" }}>
                <input type="hidden" name="number" value={number} />
                <input type="hidden" name="section" value={section.key} />
                <button
                  type="submit"
                  style={{ ...small, color: "var(--viol)" }}
                  title={t("postMortem.regenerateSection")}
                >
                  ✦ {section.body ? t("ai.regenerate") : t("ai.generate")}
                </button>
              </form>
            )}
          </>
        )}
      </div>
      {editing ? (
        <form
          action={async (fd) => {
            await savePostMortemSection(fd);
            setEditing(false);
          }}
          style={{ display: "flex", flexDirection: "column", gap: 8 }}
        >
          <input type="hidden" name="number" value={number} />
          <input type="hidden" name="section" value={section.key} />
          <textarea
            name="body"
            defaultValue={section.body}
            rows={Math.min(14, Math.max(4, section.body.split("\n").length + 1))}
            autoFocus
            className="oi-field"
            style={{
              border: "1px solid var(--line)",
              borderRadius: 10,
              padding: "10px 13px",
              fontSize: 13.5,
              lineHeight: 1.6,
              resize: "vertical",
              outline: "none",
              background: "var(--panel)",
              fontFamily: "inherit",
            }}
          />
          <div style={{ display: "flex", gap: 8 }}>
            <button
              type="submit"
              style={{
                height: 30,
                padding: "0 12px",
                borderRadius: 8,
                background: "var(--brand)",
                color: "#fff",
                border: 0,
                fontSize: 12.5,
                fontWeight: 600,
                cursor: "pointer",
              }}
            >
              {t("common.save")}
            </button>
            <button
              type="button"
              onClick={() => setEditing(false)}
              style={{
                height: 30,
                padding: "0 11px",
                borderRadius: 8,
                border: "1px solid var(--line)",
                background: "var(--panel)",
                fontSize: 12.5,
                cursor: "pointer",
              }}
            >
              {t("common.cancel")}
            </button>
          </div>
        </form>
      ) : section.body.trim() === "" ? (
        <p style={{ margin: "0 0 4px", fontSize: 13, color: "var(--ink-3)", fontStyle: "italic" }}>
          {t("postMortem.emptySection")}
        </p>
      ) : section.body.startsWith("- ") ? (
        <ul
          style={{
            margin: 0,
            paddingLeft: 20,
            fontSize: 13.5,
            color: "var(--ink-2)",
            lineHeight: 1.65,
          }}
        >
          {section.body.split("\n").map((line, i) => (
            <li key={i}>{line.replace(/^- /, "")}</li>
          ))}
        </ul>
      ) : (
        <p
          style={{
            margin: 0,
            fontSize: 13.5,
            color: "var(--ink-2)",
            lineHeight: 1.65,
            textWrap: "pretty",
            whiteSpace: "pre-wrap",
          }}
        >
          {section.body}
        </p>
      )}
    </div>
  );
}
